apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: multi-env
  namespace: argocd
spec:
  description: Multi-environment applications project
  sourceRepos:
    - 'https://github.com/romainfaure-ascenzia/gitops-2'
  destinations:
    - namespace: 'dev'
      server: https://kubernetes.default.svc
    - namespace: 'staging'
      server: https://kubernetes.default.svc
    - namespace: 'prod'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
  orphanedResources:
    warn: true
